services:
  openclaw:
    build: .
    environment:
      TERM: xterm-256color
      # Tailscale
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_HOSTNAME: ${TS_HOSTNAME:-openclaw}
      # Openclaw
      OPENCLAW_STATE_DIR: /openclaw/.openclaw
      # API Keys
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      COPILOT_GITHUB_TOKEN: ${COPILOT_GITHUB_TOKEN}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      XAI_API_KEY: ${XAI_API_KEY}
      BRAVE_API_KEY: ${BRAVE_API_KEY}
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - openclaw-tailscale-state:/var/lib/tailscale
      - openclaw-data:/openclaw
    init: true
    restart: unless-stopped

volumes:
  openclaw-data: null
  openclaw-tailscale-state: null
